### ISSUE TITLE
Vec2 - getOpposite shouldn't take an argument

### ISSUE THREAD

**Issue by erikwatson** [erikwatson/Bramble#48]
Currently the Vec2 has a getOpposite function that takes a Vec2 as an argument, this isn't used for anything. 
The function getOpposite should just return the opposite of it's existing value, not of any arbitrary Vec2 we have.

**Comment by MohitKambli** [comment]
Hello @erikwatson,
Hope you're doing well.
Could I possibly work on this issue?

Thanks and Regards,
Mohit Kambli
